acme_fish_block_category:
    resource: "@AcmeFishBlockBundle/Controller/CategoryController.php"
    type:     annotation

acme_fish_block:
    resource: "@AcmeFishBlockBundle/Resources/config/routing.yml"
    prefix:   /

