acme_fish_block_acteurs:
    resource: "@AcmeFishBlockBundle/Controller/ActeursController.php"
    type:     annotation

acme_fish_block_seasion:
    resource: "@AcmeFishBlockBundle/Controller/SeasonController.php"
    type:     annotation

acme_fish_block_episode:
    resource: "@AcmeFishBlockBundle/Controller/EpisodeController.php"
    type:     annotation

acme_fish_block_category:
    resource: "@AcmeFishBlockBundle/Controller/CategoryController.php"
    type:     annotation

acme_fish_block:
    resource: "@AcmeFishBlockBundle/Resources/config/routing.yml"

