<?php

namespace Acme\FishBlockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function fetchAllWithSeriesCount()
    {
        /* Création de la requète avec le query builder */
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select("c as category, count(f) as nbConcernedSeries")
            ->from("AcmeFishBlockBundle:Category", "c")
            ->leftJoin("c.serie", "f")
            ->groupBy("c");
        /* On retourne les enregistrements, il s'agira d'un table multidimentionnel
         * Le premier paramètre "category" contiendra notre entité category
         * Le 2ème paramètre nbConcernedSeries contient le nombre de series de la categorie
         * On aurait pu tout simplement faire un findAll() en y mettant une jointure et compter
         * simplement le nombre de la categorie associées, mais cela chargerait les données des categories qui
         * nous sont ici inutiles.
         */
        return $queryBuilder->getQuery()->getResult();

    }

}
