fos_user:
    profile:
            form:
                type: Acme\FishBlockBundle\Form\ProfileType
    registration:
            form:
                type: Acme\FishBlockBundle\Form\RegistrationType
    user_class:             ~ # Required
    use_listener:           true
    use_flash_notifications: true
    use_username_form_type: true
    model_manager_name:     null  # change it to the name of your entity/document manager if you don't want to use the default one.
    from_email:
        address:        noreply@fishblock.com
        sender_name:    Demo Test
    profile:
        form:
            type:               FOS\UserBundle\Form\Type\ProfileFormType # or 'fos_user_profile' on Symfony < 2.8
            name:               fos_user_profile_form
            validation_groups:  [Profile, Default]
    change_password:
        form:
            type:               FOS\UserBundle\Form\Type\ChangePasswordFormType # or 'fos_user_change_password' on Symfony < 2.8
            name:               fos_user_change_password_form
            validation_groups:  [ChangePassword, Default]
    registration:
        confirmation:
            from_email: # Use this node only if you don't want the global email address for the confirmation email
                address:        noreply@fishblock.com
                sender_name:    Registration
            template:   FOSUserBundle:Registration:email.txt.twig
            enabled:    false # change to true for required email confirmation
        form:
            type:               FOS\UserBundle\Form\Type\RegistrationFormType # or 'fos_user_registration' on Symfony < 2.8
            name:               fos_user_registration_form
            validation_groups:  [Registration, Default]
    resetting:
        token_ttl: 86400
        email:
            from_email: # Use this node only if you don't want the global email address for the resetting email
                address:        noreply@fishblock.com
                sender_name:    Resetting
            template:   email/password_resetting.email.twig
        form:
            type:               FOS\UserBundle\Form\Type\ResettingFormType # or 'fos_user_resetting' on Symfony < 2.8
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]
    service:
        mailer:                 fos_user.mailer.twig_swift
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default


# Vich Uploader Configuration
vich_uploader:
    db_driver: orm
    mappings:
            _images:
                uri_prefix:         '%app.path.serie_images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images'

# EasyAdmin configuration
easy_admin:
    site_name:  'public/images/logo-fishblock2.png'
    list:
      max_results: 10
      actions:
         - { name: 'show', icon: 'eye' }
         - { name: 'edit', icon: 'pencil' }
         - { name: 'delete', icon: 'remove'}
    design:
      form_theme:   'vertical'
      brand_color: '#48B9C7'
      color_scheme: 'light'
      menu:
        - { entity: 'Customer', icon: 'cogs' }
        - { entity: 'User', icon: 'users' }
        - { entity: 'Category', icon: 'tags' }
        - { entity: 'Series', icon: 'youtube-play' }
        - { entity: 'Season', icon: 'modx' }
        - { entity: 'Episode', icon: 'caret-square-o-right' }
        - { entity: 'Acteurs', icon: 'street-view' }

    entities:
            Customer:
                 class: Acme\FishBlockBundle\Entity\Customer
                 form:
                      fields:
                        - { type: 'group', css_class: 'col-sm-6', label: 'Basic information', icon: 'pencil' }
                        - name
                        - { type: 'group', css_class: 'col-sm-6', label: 'Select user', icon: 'user' }
                        - user


            User:
                class: Acme\FishBlockBundle\Entity\User
                title: 'Users'
                form:
                    fields:
                        - { type: 'group', css_class: 'col-sm-6', label: 'Basic information', icon: 'pencil' }
                        - customers
                        - username
                        - email
                        - { property: 'imageFile', type: 'vich_image' }
                        - { property: 'date_nais', type: 'date', format: 'j/m/Y', label: 'Date de naissance' }
                        - { type: 'group', css_class: 'col-sm-6', label: 'Stats user', icon: 'cube' }
                        - enabled
                        - { property: 'password', algorithm: 'bcrypt', cost: 12 }
                        - roles
                list:
                    fields:
                        - { property: 'id', type: 'int'}
                        - { property: 'image', type: 'image', base_path: '%app.path.serie_images%' }
                        - { property: 'username', type: 'text'}
                        - { property: 'email', type: 'email'}
                        - { property: 'roles', type: 'array'}
                        - { property: 'date_nais', type: 'date', format: 'd M Y'}
                        - { property: 'enabled', type: 'toggle'}
                        - { property: 'last_login', type: 'datetime'}
#                        - { property: 'locked', type: 'boolean'}

            Series:
                class: Acme\FishBlockBundle\Entity\Series
                form:
                    fields:
                        - { type: 'group', css_class: 'col-sm-6', label: 'Basic information', icon: 'pencil' }
                        - titre
                        - { property: 'description', type: 'ckeditor' }
                        - { property: 'imageFile', type: 'vich_image' }
                        - { type: 'group', css_class: 'col-sm-6', label: 'Others information', icon: 'coube' }
                        - auteur
                        - acteurs
                        - season
                        - category
                list:
                    fields:
                        - { property: 'id', type: 'int'}
                        - { property: 'image', type: 'image', base_path: '%app.path.serie_images%' }
                        - { property: 'titre', type: 'text' }
                        - { property: 'auteur', type: 'text' }
                        - { property: 'acteurs', type: 'association', entity: 'acteurs' }
                        - { property: 'season', type: 'association', entity: 'season' }
                        - { property: 'category', type: 'association', entity: 'category' }

            Season:
                class: Acme\FishBlockBundle\Entity\Season

            Episode:
                class: Acme\FishBlockBundle\Entity\Episode

            Category:
                class: Acme\FishBlockBundle\Entity\Category

            Acteurs:
                class: Acme\FishBlockBundle\Entity\Acteurs
                form:
                    fields:
                        - { type: 'group', css_class: 'col-sm-6', label: 'Basic information', icon: 'pencil' }
                        - name
                        - pseudo
                        - serie
                        - { property: 'resume', type: 'ckeditor' }
                        - { type: 'group', css_class: 'col-sm-6', label: 'Others informations', icon: 'cube' }
                        - { property: 'imageFile', type: 'vich_image' }
                        - { property: 'date_nais', type: 'datetime', format: 'd/n/Y', label: 'Date de naissance' }
                        - taille

                list:
                    fields:
                        - { property: 'id', type: 'int'}
                        - name
                        - pseudo
                        - { property: 'date_nais', type: 'date', format: 'd M Y'}
                        - taille
                        - { property: 'image', type: 'image', base_path: '%app.path.serie_images%' }







