# Acme/FishBlockBundle/Resources/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_index:
    resource: "@AcmeFishBlockBundle/Controller/"
    type:     annotation
    prefix:   /

_admin_category:
    resource: "@AcmeFishBlockBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /admin

_admin_serie:
    resource: "@AcmeFishBlockBundle/Controller/SerieController.php"
    type:     annotation
    prefix:   /admin

fish_admin:
    path: /admin
    defaults: { _controller: AcmeFishBlockBundle:Admin:index}

_series:
    resource: "@AcmeFishBlockBundle/Controller/SerieController.php"
    type:     annotation
    prefix:   /

acme_fish_block_proposer:
    resource: "@AcmeFishBlockBundle/Controller/ProposerController.php"
    type:     annotation

_langue:
    path: /{langue}
    defaults: { _controller: AcmeFishBlockBundle:Default:index}
    requirements:
            langue: fr|en