# Acme/FishBlockBundle/Resources/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_index:
    resource: "@AcmeFishBlockBundle/Controller/"
    type:     annotation
    prefix:   /

_admin_genre:
    resource: "@AcmeFishBlockBundle/Controller/GenreController.php"
    type:     annotation
    prefix:   /admin

_admin_serie:
    resource: "@AcmeFishBlockBundle/Controller/SerieController.php"
    type:     annotation
    prefix:   /admin

fish_admin:
    path: /admin
    defaults: { _controller: AcmeFishBlockBundle:Admin:index}

_series:
    resource: "@AcmeFishBlockBundle/Controller/SerieController.php"
    type:     annotation
    prefix:   /