# Acme/FishBlockBundle/Resources/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_index:
    resource: "@AcmeFishBlockBundle/Controller/"
    type:     annotation
    prefix:   /

_admin_category:
    resource: "@AcmeFishBlockBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /admin

_admin_serie:
    resource: "@AcmeFishBlockBundle/Controller/SerieController.php"
    type:     annotation
    prefix:   /admin

