# app/config/services.yml
services:


#  Services locale translation configuration
    app.locale_listener:
        class: Acme\FishBlockBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }