# app/config/services.yml
services:
    # ...
    app.images_uploader:
        class: Acme\FishBlockBundle\FileUploader
        arguments: ['%images_serie_directory%']

    app.doctrine_images_listener:
            class: Acme\FishBlockBundle\EventListener\ImageUploadListener
            arguments: ['@app.images_uploader']
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }

    app.locale_listener:
        class: Acme\FishBlockBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }